### ISSUE TITLE
Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: No module named pcapy

### ISSUE THREAD

**Issue by freetest** [allfro/sploitego#1]
Mac:pentest www$ canari install-package sploitego
Multiple versions of Maltego detected: 
[0] Maltego v1.0.1CaseFileCE
[1] Maltego v3.4.0
[2] Maltego v3.4.0CE
Please select which version you wish to use [0]: 1
Looking for transforms in sploitego.transforms
Does not appear to be a valid canari package. Couldn't import the 'sploitego.transforms' package in 'sploitego'. Error message: No module named pcapy

i really installed pcapy.

Mac:~ www$ port installed | grep pcapy
  py-pcapy @0.10.5_0 (active)
  py24-pcapy @0.10.5_0 (active)
  py26-pcapy @0.10.5_0 (active)
  py27-pcapy @0.10.5_0 (active)

need your help.

**Comment by allfro** [comment]
Hi @freetest 

Make sure you use pylibpcap as specified in the scapy documentation. You'll want to take a look at all the requirements for scapy from here: http://www.secdev.org/projects/scapy/doc/installation.html. Make sure you follow the instructions there and you should be good on the requirements front. Also, I noticed you're using homebrew or macports. You'll want to ensure that the python interpreter being launched by root is the same as the one being launched by the regular user. You can do this by doing `which python` and `sudo which python`. If you see a different output in the sudo'd version that means you are invoking a different python interpreter with a different path that doesn't have all the requirements installed in its site-path. A simple fix would be to reorder your PATH variable in root to have the PATH of the macports python interpreter come up first. Hope this helps!

Cheers,

Nadeem

**Comment by allfro** [comment]
Looks like you've misspelled sploitego. It says sploitgeo above.

**Comment by freetest** [comment]
@allfro   sorry

i't can't work on tungsten ce 3.4.1?

 i work is on 3.1.1 is ok.

![qq20131213-2](https://f.cloud.github.com/assets/5380255/1742506/53f082b6-63fd-11e3-8842-1ef01d28cd7d.png)

![qq20131213-1](https://f.cloud.github.com/assets/5380255/1742508/5e551a46-63fd-11e3-8c12-182d572aa8b0.png)

![qq20131213-3](https://f.cloud.github.com/assets/5380255/1742510/6562d454-63fd-11e3-8792-2d7ccba11050.png)

**Comment by allfro** [comment]
Hi @freetest

You need to use the create-profile command for tungsten and manually import the generated .mtz file. Please ensure you have the latest version of Canari installed.

Cheers

Nadeem.

**Comment by allfro** [comment]
Use `canari create-profile sploitego` and then import the sploitego.mtz file in Tungsten.

**Comment by allfro** [comment]
That's a different command that does a completely different function. You want create-profile not create-package

**Comment by freetest** [comment]
@allfro 
thanks very much, i got it .

**Comment by freetest** [comment]
@allfro 

thanks, very much. i got it

**Comment by AnonKiller1036** [comment]
Would you mind sending me the sploitego.mtz file? It seems that my canari doesn't have the create-profile command.
